"""Local Qiskit execution environment for the gowithquantum agent.

Exposes a single function, :func:`run_quantum_circuit`, which executes
model-generated Qiskit code against a local Aer simulator and returns the
captured stdout plus a designated ``result`` value.

NOTE: this executes code generated by the language model in-process. That is
intentional for the MVP — the whole point is to run generated quantum code —
but it is NOT a security boundary. Before exposing this to untrusted input,
run it inside a real sandbox (container, gVisor, restricted seccomp, etc.).
"""

from __future__ import annotations

import contextlib
import io
import textwrap
import traceback
from typing import Any

_MAX_STDOUT_CHARS = 20_000

# Names made available to every executed snippet so Claude does not have to
# re-import the basics. Code may still import anything else from qiskit.
_ENV_SETUP = textwrap.dedent(
    """
    import numpy as np
    from qiskit import QuantumCircuit, transpile
    from qiskit_aer import AerSimulator
    from qiskit.quantum_info import Statevector, Operator, DensityMatrix

    # A ready-to-use local simulator. Code may also create its own.
    simulator = AerSimulator()
    """
)


def _serialize(obj: Any, _depth: int = 0) -> Any:
    """Best-effort conversion of Qiskit / NumPy objects into JSON-safe values."""
    if _depth > 6:
        return str(obj)
    if obj is None or isinstance(obj, (bool, int, float, str)):
        return obj
    if isinstance(obj, complex):
        return {"real": obj.real, "imag": obj.imag}

    # NumPy scalars / arrays.
    try:
        import numpy as np

        if isinstance(obj, np.generic):
            return _serialize(obj.item(), _depth + 1)
        if isinstance(obj, np.ndarray):
            return [_serialize(x, _depth + 1) for x in obj.tolist()]
    except Exception:
        pass

    # Qiskit Statevector / DensityMatrix expose a NumPy array on .data
    if obj.__class__.__name__ in {"Statevector", "DensityMatrix"}:
        data = getattr(obj, "data", None)
        if data is not None:
            return _serialize(data, _depth + 1)

    if isinstance(obj, dict):
        return {str(k): _serialize(v, _depth + 1) for k, v in obj.items()}
    if isinstance(obj, (list, tuple, set)):
        return [_serialize(x, _depth + 1) for x in obj]

    # Counts and other dict-like results.
    if hasattr(obj, "items"):
        try:
            return {str(k): _serialize(v, _depth + 1) for k, v in obj.items()}
        except Exception:
            pass

    return str(obj)


def _truncate(text: str) -> str:
    if len(text) > _MAX_STDOUT_CHARS:
        return text[:_MAX_STDOUT_CHARS] + "\n... [stdout truncated] ..."
    return text


def run_quantum_circuit(code: str) -> dict:
    """Execute ``code`` in a fresh namespace and capture stdout + ``result``.

    Returns a JSON-serialisable dict with ``ok`` and either ``result``/``stdout``
    or ``error``. Never raises — failures are reported back to the model so it
    can fix its code and retry.
    """
    namespace: dict = {}
    try:
        exec(_ENV_SETUP, namespace)
    except Exception as exc:  # pragma: no cover - environment problem
        return {
            "ok": False,
            "error": (
                "Quantum environment failed to initialise. Are qiskit and "
                f"qiskit-aer installed? Details: {exc}"
            ),
            "stdout": "",
        }

    stdout = io.StringIO()
    try:
        with contextlib.redirect_stdout(stdout):
            exec(code, namespace)
    except Exception:
        return {
            "ok": False,
            "error": traceback.format_exc(limit=5),
            "stdout": _truncate(stdout.getvalue()),
        }

    result = namespace.get("result", None)
    payload: dict = {"ok": True, "stdout": _truncate(stdout.getvalue())}
    if result is None:
        payload["result"] = None
        payload["note"] = (
            "No variable named `result` was set. Assign your key output "
            "(counts, expectation value, decoded answer, ...) to `result` so it "
            "is returned to you."
        )
    else:
        payload["result"] = _serialize(result)
    return payload
